# version: "3.8"
name: dockertut
services:
  nodeapp:
    build: 
      context: ./myapp
      dockerfile: Dockerfile
    image: dockertutapp
    container_name: samplewala
    environment:
      - PORT=4000
    env_file: 
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
  
  mongodb:
    image : mongo
    container_name: dockertutDB
    ports:
      - "27070:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME:admin
      - MONGO_INITDB_ROOT_PASSWORD:password
    volumes:
      - dockertutData:/data/db

  authservice:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - nodeapp
    environment:
      - PORT=5000

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - SERVER_url=http://localhost:4000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

    depends_on:
      - authservice
    
    develop:
      watch:
        - path: ./client/package.json
          action : rebuild
          
        - path: ./client/package-lock.json
          action : rebuild
        
        - path: ./client
        # target must be same as working directory as in Docker file
          target: /app  
          action : sync

      
volumes:
  dockertutData:
    driver: local
   
